version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "5678:8080"
    volumes:
      - ./volumes/backend:/app
      - ./volumes/avatars:/root/springboot-lib
    restart: on-failure
    command: >
      sh -c "/wait-for-it.sh db:3306 -- java -jar app.jar"

  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=java
      - MSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "3308:3306"
    restart: on-failure

  stripe:
    image: stripe/stripe-cli:v1.2.7
    command: listen --forward-to http://localhost:5678/cars/buy-premuim
    environment:
      - STRIPE_API_KEY=sk_test_51Nf481Ae4RILjJWGnrK0ByYfSZcW7FRzMZorxUraOwKjvOJEcejN4W05quGPkXf3AhJ1mtkaYgs5JvmEAonLCcpE00zeZqzgEI
      - STRIPE_DEVICE_NAME=djstripe_docker