package com.example.auto_ria.enums;

public enum EMail {
    WELCOME, PLATFORM_LEAVE, YOUR_ACCOUNT_BANNED, CHECK_ANNOUNCEMENT,
    CAR_BEING_CHECKED, CAR_BEING_BANNED, CAR_BEING_ACTIVATED,
    FORGOT_PASSWORD, ACTIVATE_ACCOUNT, REGISTER_KEY,
    PAYMENT_FAILED, PREMIUM_END,
    USERS
}
